# Generated by Django 5.2.3 on 2025-07-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_diagnosis_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sex',
            new_name='gender',
        ),
    ]
