from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path("about",views.about, name="about"),
    path("help",views.help, name="help"),
    path("contact",views.contact, name="contact"),
    path("login",views.login, name="login"),
    path("admin",views.admin, name="admin"),
    path("requestPage",views.requestPage, name="requestPage"),
    path("signupSuperUser",views.signupSuperUser, name="signupSuperUser"),
    path('delete/<int:id>', views.delete, name='delete'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('examinerPage/', views.examinerPage, name='examinerPage'),
    path('signupStudents/', views.signupStudents, name='signupStudents'),
    path('deleteStudent/<int:id>', views.deleteStudent, name='deleteStudent'),
    path('testsPage/', views.testsPage, name='testsPage'),
    path('testsPage/<int:id>', views.testsPage, name='testsPage'),
    path('startTest/', views.startTest, name='startTest'),
    path('editStudent/<int:id>', views.editStudent, name='editStudent'),
    path('startTest/<int:id>', views.startTest, name='startTest'),
    path('test1', views.primary_test1, name='test1'),
    path('test1_training/', views.primary_test1_training, name='test1_training'),
    path('test1/autosave/', views.primary_test1_autosave, name='primary_test1_autosave'),
    path('test2_training/', views.primary_test2_training, name='test2_training'),  
    path('test2', views.primary_test2, name='test2'),
    path('test3_training/', views.primary_test3_training, name='test3_training'), 
    path('test3', views.primary_test3, name='test3'),
    path('test4', views.primary_test4, name='test4'),
    path('test5_training', views.primary_test5_training, name='test5_training'),
    path('test5', views.primary_test5, name='test5'),
    path('test6_training/', views.primary_test6_training, name='test6_training'),
    path('test6', views.primary_test6, name='test6'),
    path('primary_result', views.primary_result, name='primary_result'),
    path('test1_training_sec/', views.secondary_test1_training, name='test1_training_sec'),
    path('test1_sec', views.secondary_test1, name='secondary_test1'),
    path('test2_training_sec/', views.secondary_test2_training, name='test2_training_sec'),
    path('test2_sec', views.secondary_test2, name='secondary_test2'),
    path('test3_sec', views.secondary_test3, name='secondary_test3'),
    path('test4_training_sec/', views.secondary_test4_training, name='test4_training_sec'),
    path('test4_sec', views.secondary_test4, name='secondary_test4'),
    path('studentProfile/<int:id>', views.studentProfile, name='studentProfile'),
    path('search/results', views.search_results, name='search-results'),
    path('testsPageSec/', views.testsPageSec, name='testsPageSec'),
    path('secondary_result', views.secondary_result, name='secondary_result'),

]