from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path("about",views.about, name="about"),
    path("help",views.help, name="help"),
    path("contact",views.contact, name="contact"),
    path("login",views.login, name="login"),
    path("admin",views.admin, name="admin"),

    path("requestPage",views.requestPage, name="requestPage"),
    #path("adminPage",views.adminPage, name="adminPage"),
    
    path("signupSuperUser",views.signupSuperUser, name="signupSuperUser"),
    path('delete/<int:id>', views.delete, name='delete'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('examinerPage/', views.examinerPage, name='examinerPage'),
    path('signupStudents/', views.signupStudents, name='signupStudents'),
    path('deleteStudent/<int:id>', views.deleteStudent, name='deleteStudent'),
    path('testsPage/', views.testsPage, name='testsPage'),
    path('testsPage/<int:id>', views.testsPage, name='testsPage'),
    path('startTest/', views.startTest, name='startTest'),
    path('editStudent/<int:id>', views.editStudent, name='editStudent'),
    path('startTest/<int:id>', views.startTest, name='startTest'),
    path('test1', views.primary_test1, name='test1'),
    path('test1_training/', views.primary_test1_training, name='test1_training'),
    path('test1/autosave/', views.primary_test1_autosave, name='primary_test1_autosave'),  
    path('test2', views.primary_test2, name='test2'),
    path('test3', views.primary_test3, name='test3'),
    path('test4', views.primary_test4, name='test4'),
    path('test5', views.primary_test5, name='test5'),
    path('test6', views.primary_test6, name='test6'),
    path('test1_training_sec/', views.secondary_test1_training, name='test1_training_sec'),
    path('test1_sec', views.secondary_test1, name='secondary_test1'),
    path('test2_sec', views.secondary_test2, name='secondary_test2'),
    path('test3_sec', views.secondary_test3, name='secondary_test3'),
    path('test4_sec', views.secondary_test4, name='secondary_test4'),
    
    #path('rpdNamingObjTst/<int:id>', views.rpdNamingObjTst, name='rpdNamingObjTst'),
    #path('rpdNamingObjTst/', views.rpdNamingObjTst, name='rpdNamingObjTst'),
    #path('rpdNamingObjTstB/<int:id>', views.rpdNamingObjTstB, name='rpdNamingObjTstB'),
    #path('rpdNamingObjTstB/', views.rpdNamingObjTstB, name='rpdNamingObjTstB'),
    #path('rpdNamingLtrTst/<int:id>', views.rpdNamingLtrTst, name='rpdNamingLtrTst'),
    #path('rpdNamingLtrTst/', views.rpdNamingLtrTst, name='rpdNamingLtrTst'),
    #path('rpdNamingLtrTstB/<int:id>', views.rpdNamingLtrTstB, name='rpdNamingLtrTstB'),
    #path('rpdNamingLtrTstB/', views.rpdNamingLtrTstB, name='rpdNamingLtrTstB'),
    #path('nonWordReadingAccuracy/', views.nonWordReadingAccuracy, name='nonWordReadingAccuracy'),
    path('studentProfile/<int:id>', views.studentProfile, name='studentProfile'),
    #path('phonemeSyllableDel/<int:id>', views.phonemeSyllableDel, name='phonemeSyllableDel'),
    #path('phonemeSyllableDel/', views.phonemeSyllableDel, name='phonemeSyllableDel'),
    #path('phonemSyllableTraining/<int:id>', views.phonemSyllableTraining, name='phonemSyllableTraining'),
    #path('phonemSyllableTraining/', views.phonemSyllableTraining, name='phonemSyllableTraining'),
    #path('nonWordRepetitionTraining/<int:id>', views.nonWordRepetitionTraining, name='nonWordRepetitionTraining'),
    #path('nonWordRepetitionTraining/', views.nonWordRepetitionTraining, name='nonWordRepetitionTraining'),
    #path('nonWordRepetition/<int:id>', views.nonWordRepetition, name='nonWordRepetition'),
    #path('nonWordRepetition/', views.nonWordRepetition, name='nonWordRepetition'),
    path('search/results', views.search_results, name='search-results'),
    path('testsPageSec/', views.testsPageSec, name='testsPageSec'),
    #path('phonemeSyllableTrainSec/<int:id>', views.phonemeSyllableTrainSec, name='phonemeSyllableTrainSec'),
    #path('phonemeSyllableTrainSec/', views.phonemeSyllableTrainSec, name='phonemeSyllableTrainSec'), 
    #path('phonemeSyllableDelSec/', views.phonemeSyllableDelSec, name='phonemeSyllableDelSec'),
    #path('rpdNamingObjSecA/', views.rpdNamingObjSecA, name='rpdNamingObjSecA'),
    #path('rpdNamingObjSecB/', views.rpdNamingObjSecB, name='rpdNamingObjSecB'),
    #path('nonWordRepTrainingSec/<int:id>', views.nonWordRepTrainingSec, name='nonWordRepTrainingSec'),
    #path('nonWordRepTrainingSec/', views.nonWordRepTrainingSec, name='nonWordRepTrainingSec'),
    #path('nonWordRepSec/<int:id>', views.nonWordRepSec, name='nonWordRepSec'),
    #path('nonWordRepSec/', views.nonWordRepSec, name='nonWordRepSec'), 
    #path('nonWordReadingAccuracySec/', views.nonWordReadingAccuracySec, name='nonWordReadingAccuracySec'),
    #path('showREC/', views.showREC, name='showREC'),
    #path('showRECsec/', views.showRECsec, name='showRECsec')
]