# Generated by Django 5.2.3 on 2025-07-02 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('speciality', models.CharField(max_length=60)),
                ('organization', models.CharField(max_length=60)),
                ('stage', models.CharField(choices=[('PRIMARY', 'Primary School'), ('SECONDARY', 'Secondary School'), ('BOTH', 'Primary/Secondary')], default='PRIMARY', max_length=20)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_id', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=60)),
                ('sex', models.CharField(max_length=60)),
                ('schoolName', models.CharField(max_length=60)),
                ('grade', models.CharField(max_length=60)),
                ('civilID', models.IntegerField()),
                ('eduDistrict', models.CharField(max_length=60)),
                ('nationality', models.CharField(max_length=60)),
                ('examDate', models.DateField(max_length=60)),
                ('birthDate', models.DateField(max_length=60)),
                ('age', models.CharField(max_length=60)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examiner_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RpdNamingObjSec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startT_A', models.DateTimeField(null=True)),
                ('endT_A', models.DateTimeField(null=True)),
                ('wrongAns_A', models.IntegerField(null=True)),
                ('reason_A', models.CharField(max_length=60, null=True)),
                ('startT_B', models.DateTimeField(null=True)),
                ('endT_B', models.DateTimeField(null=True)),
                ('wrongAns_B', models.IntegerField(null=True)),
                ('reason_B', models.CharField(max_length=60, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diagnosis_test.student')),
            ],
        ),
        migrations.CreateModel(
            name='RpdNamingObj_Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startT_A', models.DateTimeField(null=True)),
                ('endT_A', models.DateTimeField(null=True)),
                ('wrongAns_A', models.IntegerField(null=True)),
                ('reason_A', models.CharField(max_length=60, null=True)),
                ('startT_B', models.DateTimeField(null=True)),
                ('endT_B', models.DateTimeField(null=True)),
                ('wrongAns_B', models.IntegerField(null=True)),
                ('reason_B', models.CharField(max_length=60, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diagnosis_test.student')),
            ],
        ),
        migrations.CreateModel(
            name='RpdNamingLtrs_Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startT_A', models.DateTimeField(null=True)),
                ('endT_A', models.DateTimeField(null=True)),
                ('wrongAns_A', models.IntegerField(null=True)),
                ('reason_A', models.CharField(max_length=60, null=True)),
                ('startT_B', models.DateTimeField(null=True)),
                ('endT_B', models.DateTimeField(null=True)),
                ('wrongAns_B', models.IntegerField(null=True)),
                ('reason_B', models.CharField(max_length=60, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diagnosis_test.student')),
            ],
        ),
        migrations.CreateModel(
            name='PhonemeSyllableDelSec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctAns', models.IntegerField(null=True)),
                ('reason', models.CharField(max_length=60, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diagnosis_test.student')),
            ],
        ),
        migrations.CreateModel(
            name='PhonemeSyllableDel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctAns', models.IntegerField(null=True)),
                ('reason', models.CharField(max_length=60, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diagnosis_test.student')),
            ],
        ),
        migrations.CreateModel(
            name='NonWordRepetitionSec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctAns', models.IntegerField(null=True)),
                ('reason', models.CharField(max_length=60, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diagnosis_test.student')),
            ],
        ),
        migrations.CreateModel(
            name='NonWordRepetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctAns', models.IntegerField(null=True)),
                ('reason', models.CharField(max_length=60, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diagnosis_test.student')),
            ],
        ),
        migrations.CreateModel(
            name='NonWordReadingAccSec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctAns', models.IntegerField(null=True)),
                ('reason', models.CharField(max_length=60, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diagnosis_test.student')),
            ],
        ),
        migrations.CreateModel(
            name='NonWordReadingAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctAns', models.IntegerField(null=True)),
                ('reason', models.CharField(max_length=60, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diagnosis_test.student')),
            ],
        ),
        migrations.CreateModel(
            name='finalReportSecondary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('strength', models.TextField()),
                ('weakness', models.TextField()),
                ('results', models.TextField()),
                ('suggestion', models.TextField()),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examiner_idS', to='electronic_diagnosis_test.examiner')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_idS', to='electronic_diagnosis_test.student')),
            ],
        ),
        migrations.CreateModel(
            name='finalReportPrimary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_1_skill_sound', models.BooleanField(null=True)),
                ('test_2_skill_sound', models.BooleanField(null=True)),
                ('test_3_skill_speed', models.BooleanField(null=True)),
                ('test_4_skill_speed', models.BooleanField(null=True)),
                ('test_5_skill_memory', models.BooleanField(null=True)),
                ('notes', models.TextField()),
                ('strength', models.TextField()),
                ('weakness', models.TextField()),
                ('result', models.TextField()),
                ('suggestion', models.TextField()),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examiner_ids', to='electronic_diagnosis_test.examiner')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_ids', to='electronic_diagnosis_test.student')),
            ],
        ),
    ]
