# Generated by Django 5.2.3 on 2025-09-27 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('speciality', models.CharField(max_length=60)),
                ('organization', models.CharField(max_length=60)),
                ('stage', models.CharField(choices=[('PRIMARY', 'Primary School'), ('SECONDARY', 'Secondary School'), ('BOTH', 'Primary/Secondary')], default='PRIMARY', max_length=20)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_id', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=60)),
                ('schoolName', models.CharField(max_length=60)),
                ('grade', models.CharField(max_length=60)),
                ('civilID', models.IntegerField()),
                ('eduDistrict', models.CharField(max_length=60)),
                ('nationality', models.CharField(max_length=60)),
                ('examDate', models.DateField(max_length=60)),
                ('birthDate', models.DateField(max_length=60)),
                ('age', models.CharField(max_length=60)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examiner_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryTest4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_scores', models.JSONField()),
                ('total_correct', models.PositiveIntegerField()),
                ('durations', models.JSONField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('total_time_secs', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diagnosis_test.student')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryTest3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_scores', models.JSONField()),
                ('total_correct', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diagnosis_test.student')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryTest2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_scores', models.JSONField()),
                ('total_correct', models.PositiveIntegerField()),
                ('durations', models.JSONField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('total_time_secs', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diagnosis_test.student')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryTest1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_correct', models.PositiveIntegerField()),
                ('time_seconds', models.FloatField()),
                ('fluency_score', models.FloatField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diagnosis_test.student')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryTest6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_scores', models.JSONField()),
                ('total_correct', models.PositiveIntegerField()),
                ('durations', models.JSONField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('total_time_secs', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diagnosis_test.student')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryTest5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_scores', models.JSONField()),
                ('total_correct', models.PositiveIntegerField()),
                ('durations', models.JSONField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('total_time_secs', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diagnosis_test.student')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryTest4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_scores', models.JSONField()),
                ('total_correct', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diagnosis_test.student')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryTest3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_scores', models.JSONField()),
                ('total_correct', models.PositiveIntegerField()),
                ('durations', models.JSONField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('total_time_secs', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diagnosis_test.student')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryTest2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField()),
                ('total_score', models.PositiveIntegerField()),
                ('time_seconds', models.FloatField()),
                ('fluency_score', models.FloatField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diagnosis_test.student')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryTest1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_correct', models.PositiveIntegerField()),
                ('time_seconds', models.FloatField()),
                ('fluency_score', models.FloatField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diagnosis_test.student')),
            ],
        ),
    ]
