# Generated by Django 5.2.3 on 2025-09-27 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_diagnosis_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_1_skill', models.BooleanField(null=True)),
                ('test_2_skill', models.BooleanField(null=True)),
                ('test_3_skill', models.BooleanField(null=True)),
                ('test_4_skill', models.BooleanField(null=True)),
                ('test_5_skill', models.BooleanField(null=True)),
                ('test_6_skill', models.BooleanField(null=True)),
                ('notes', models.TextField()),
                ('strength', models.TextField()),
                ('weakness', models.TextField()),
                ('result', models.TextField()),
                ('suggestion', models.TextField()),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examiner_ids', to='electronic_diagnosis_test.examiner')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_ids', to='electronic_diagnosis_test.student')),
            ],
        ),
    ]
