# Generated by Django 5.2.3 on 2025-09-29 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_diagnosis_test', '0002_primaryresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('strength', models.TextField()),
                ('weakness', models.TextField()),
                ('result', models.TextField()),
                ('suggestion', models.TextField()),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diagnosis_test.examiner')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diagnosis_test.student')),
            ],
        ),
    ]
