# Generated by Django 5.2.3 on 2025-10-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_diagnosis_test', '0003_secondaryresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='civilID',
            field=models.CharField(max_length=20),
        ),
    ]
