# Generated by Django 5.2.3 on 2025-07-10 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_diagnosis_test', '0003_primarytest1'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryTest1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_correct', models.PositiveIntegerField()),
                ('time_seconds', models.FloatField()),
                ('fluency_score', models.FloatField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diagnosis_test.student')),
            ],
        ),
    ]
