# Generated by Django 5.2.3 on 2025-07-24 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_diagnosis_test', '0004_secondarytest1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalreportsecondary',
            name='examiner',
        ),
        migrations.RemoveField(
            model_name='finalreportsecondary',
            name='student',
        ),
        migrations.RemoveField(
            model_name='nonwordreadingacc',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='nonwordreadingaccsec',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='nonwordrepetition',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='nonwordrepetitionsec',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='phonemesyllabledel',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='phonemesyllabledelsec',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='rpdnamingltrs_score',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='rpdnamingobj_score',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='rpdnamingobjsec',
            name='student_id',
        ),
        migrations.CreateModel(
            name='PrimaryTest2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField()),
                ('total_score', models.PositiveIntegerField()),
                ('time_seconds', models.FloatField()),
                ('fluency_score', models.FloatField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diagnosis_test.student')),
            ],
        ),
        migrations.DeleteModel(
            name='finalReportPrimary',
        ),
        migrations.DeleteModel(
            name='finalReportSecondary',
        ),
        migrations.DeleteModel(
            name='NonWordReadingAcc',
        ),
        migrations.DeleteModel(
            name='NonWordReadingAccSec',
        ),
        migrations.DeleteModel(
            name='NonWordRepetition',
        ),
        migrations.DeleteModel(
            name='NonWordRepetitionSec',
        ),
        migrations.DeleteModel(
            name='PhonemeSyllableDel',
        ),
        migrations.DeleteModel(
            name='PhonemeSyllableDelSec',
        ),
        migrations.DeleteModel(
            name='RpdNamingLtrs_Score',
        ),
        migrations.DeleteModel(
            name='RpdNamingObj_Score',
        ),
        migrations.DeleteModel(
            name='RpdNamingObjSec',
        ),
    ]
