# Generated by Django 5.2.3 on 2025-08-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_diagnosis_test', '0009_primarytest3'),
        ('electronic_diagnosis_test', '0009_primarytest3_primarytest5'),
        ('electronic_diagnosis_test', '0009_secondarytest4'),
    ]

    operations = [
    ]
