# Generated by Django 5.2.3 on 2025-08-17 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_diagnosis_test', '0010_merge_0009_heads'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryTest6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_scores', models.JSONField()),
                ('total_correct', models.PositiveIntegerField()),
                ('durations', models.JSONField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('total_time_secs', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_diagnosis_test.student')),
            ],
        ),
    ]
